#!/usr/bin/env python3
"""Embed the baked PBR texture sets and the rendered sky HDRI as data URIs.

    python3 tools/embed_textures.py --tex build/tex --sky build/sky.hdr --out assets/textures.js

Produces `window.LAXFOO_TEX = { sky: "data:...", sets: { wood: {albedo, normal, rough}, ... } }`
so the game runs from file:// and bundles into a single artifact file.
"""
import argparse, base64, glob, json, os

ap = argparse.ArgumentParser()
ap.add_argument("--tex", default="build/tex")
ap.add_argument("--sky", default="build/sky.hdr")
ap.add_argument("--out", default="assets/textures.js")
a = ap.parse_args()

def data_uri(path, mime):
    return "data:%s;base64,%s" % (mime, base64.b64encode(open(path, "rb").read()).decode())

sets = {}
for p in sorted(glob.glob(os.path.join(a.tex, "*_albedo.jpg"))):
    name = os.path.basename(p)[:-len("_albedo.jpg")]
    s = {}
    for k in ("albedo", "normal", "rough"):
        f = os.path.join(a.tex, "%s_%s.jpg" % (name, k))
        if os.path.exists(f): s[k] = data_uri(f, "image/jpeg")
    sets[name] = s
sky = data_uri(a.sky, "image/vnd.radiance") if os.path.exists(a.sky) else None

os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
with open(a.out, "w") as f:
    f.write("// LaxFoo Racing textures — baked in Blender/Cycles by tools/blender_textures.py (albedo /\n"
            "// tangent normal / roughness per material, seamless via a UV-torus bake) plus the sky\n"
            "// HDRI rendered by tools/blender_sky.py. Embedded as data URIs; generated by\n"
            "// tools/embed_textures.py — do not edit by hand.\n")
    f.write("window.LAXFOO_TEX = " + json.dumps({"sky": sky, "sets": sets}) + ";\n")
print("%s written: %d texture sets, sky=%s, %.2f MB" % (a.out, len(sets), bool(sky), os.path.getsize(a.out) / 1e6))
