#!/usr/bin/env bash
# Rebuild all 3D assets: Blender (bpy) -> GLB -> gltf-transform quantize -> assets/models.js
# Requires: pip install bpy ; npm i -g @gltf-transform/cli   (or npx)
set -euo pipefail
cd "$(dirname "$0")/.."
RAW=build/models; OPT=build/opt
rm -rf "$RAW" "$OPT"; mkdir -p "$RAW" "$OPT"
python3 tools/blender_build.py --out "$RAW"
for f in "$RAW"/*.glb; do
  n=$(basename "$f")
  case "$n" in
    driver*) npx gltf-transform simplify --ratio 0.55 --error 0.0015 "$f" "$OPT/s-$n" >/dev/null
             npx gltf-transform quantize "$OPT/s-$n" "$OPT/$n" >/dev/null; rm "$OPT/s-$n";;
    *)       npx gltf-transform quantize "$f" "$OPT/$n" >/dev/null;;   # no weld: it would smear the beveled hard edges
  esac
done
python3 - <<'PY'
import base64, json, glob, os
models={os.path.basename(p)[:-4]:"data:model/gltf-binary;base64,"+base64.b64encode(open(p,'rb').read()).decode() for p in sorted(glob.glob('build/opt/*.glb'))}
open('assets/models.js','w').write(
 "// LaxFoo Racing 3D assets — generated by tools/blender_build.py (Blender 5.0 headless),\n"
 "// quantized with gltf-transform and embedded as data URIs so the game runs from file://\n"
 "// and bundles into a single artifact file. Keys: one vehicle per rig id in CARS, plus\n"
 "// driverSeated, driverStanding, stick.\n"
 "window.LAXFOO_MODELS = "+json.dumps(models)+";\n")
print("assets/models.js written:", len(models), "models")
PY
