#!/usr/bin/env bash
# Rebuild every generated asset:
#   Blender (bpy) models  -> GLB -> gltf-transform (quantize; drivers also simplified) -> assets/models.js
#   Blender/Cycles bakes  -> albedo / normal / roughness JPEG sets  ┐
#   Blender/Cycles sky    -> equirectangular HDRI                    ┴-> assets/textures.js
# Requires: pip install bpy ; npm i -g @gltf-transform/cli   (or npx)
set -euo pipefail
cd "$(dirname "$0")/.."
RAW=build/models; OPT=build/opt; TEX=build/tex; SKY=build/sky.hdr
rm -rf "$RAW" "$OPT" "$TEX"; mkdir -p "$RAW" "$OPT" "$TEX"

python3 tools/blender_build.py --out "$RAW"
for f in "$RAW"/*.glb; do
  n=$(basename "$f")
  case "$n" in
    driver*) npx gltf-transform simplify --ratio 0.55 --error 0.0015 "$f" "$OPT/s-$n" >/dev/null
             npx gltf-transform quantize "$OPT/s-$n" "$OPT/$n" >/dev/null; rm "$OPT/s-$n";;
    *)       npx gltf-transform quantize "$f" "$OPT/$n" >/dev/null;;   # no weld: it would smear the beveled hard edges
  esac
done
python3 - <<'PY'
import base64, json, glob, os
models={os.path.basename(p)[:-4]:"data:model/gltf-binary;base64,"+base64.b64encode(open(p,'rb').read()).decode() for p in sorted(glob.glob('build/opt/*.glb'))}
open('assets/models.js','w').write(
 "// LaxFoo Racing 3D assets — generated by tools/blender_build.py (Blender 5.0 headless),\n"
 "// quantized with gltf-transform and embedded as data URIs so the game runs from file://\n"
 "// and bundles into a single artifact file. Keys: one vehicle per rig id in CARS, plus\n"
 "// driverSeated, driverStanding, stick.\n"
 "window.LAXFOO_MODELS = "+json.dumps(models)+";\n")
print("assets/models.js written:", len(models), "models")
PY

python3 tools/blender_textures.py --out "$TEX"
python3 tools/blender_sky.py --out "$SKY"
python3 tools/embed_textures.py --tex "$TEX" --sky "$SKY" --out assets/textures.js
